### ISSUE TITLE
@robske_110's ToDo list

### ISSUE THREAD

**Issue by robske110** [ClearSkyTeam/ClearSky#413]
Random Commits from other projects:
_https://github.com/iTXTech/Genisys/commit/97da0933c25410f8a5af69134d3212a9e0bfa57a [FLOATINGTEXT, MID, 0.15]_ **DONE**
_https://github.com/iTXTech/Genisys/commit/afb2a6be5ea41892f28df5e78eac069a397a6080 [FLOATINGTEXT, MID, 0.15_] **DONE**
_https://github.com/iTXTech/Genisys/commit/1fac23b40053f2e64abb6520e1f0f646c936533e [PROTOCOL, HIGH, CRITICAL, 0.15]_ **DONE**
https://github.com/iTXTech/Genisys/commit/b702789519131e7eb6514142383c91f5bcc129e3 [PROTOCOL, LOW, nether]
https://github.com/iTXTech/Genisys/commit/9d7eff42ac125b3109d256c19eca02e48211e007 [GENERATOR, LOW, generatorBranch]
- [ ] Redstone
  - [ ] Observer::RedstoneUpdates
  - [ ] Repeater
  - [ ] Comperator
  - [ ] Fix bugs
- [ ] Fix API-plugin-loading-system
- [ ] ~~CLIENT CRASH BRANCH FINISH~~
- [ ] ~~Fix php5 branch again~~
- [ ] AISpawningSystem
- [ ] AI
- [x] **Win10 Inventory Fixes** (Win10-fixes branch)
  - [x] **Crafting** *dktapps*
  - [x] HotBar management *dktapps*
  - [x] General Inventory TransActions *dktapps*
- [ ] Rewrite liquid flowing calculation [MAYBE]
- [x] Disable AutoUpdater
- [x] Fix php5 branch
- [x] Remove TIP Hack
- [x] AutoUpdater fix internal CheckStable check .yml https://github.com/ClearSkyTeam/ClearSky/pull/412
- [x] Weather command final fix https://github.com/ClearSkyTeam/ClearSky/commit/bce07d0d3f538ba4f6072071a32d8d7fcd0805e9
- [x] RakLib: Fix green server status https://github.com/ClearSkyTeam/ClearSky/commit/33830c1f23890affafc658781d9e68006256cd83
- [x] Fix hardening errors
- [x] Fix entity movement
- [x] Fix entity body rotation
- [x] Base work for 0.15
- [x] MineCart Container fix https://github.com/ClearSkyTeam/ClearSky/commit/c48fd0c8e10911df3c08e7640c85afaf8766da0c && https://github.com/ClearSkyTeam/ClearSky/commit/d036062e9d06c6d7d3e1d51c2e6995075f08ac25
- [x] Rewrite hardening liquid calculation https://github.com/ClearSkyTeam/ClearSky/pull/415
- [x] Fix RakLib https://github.com/ClearSkyTeam/ClearSky/pull/441
- [x] Re-Add pocketmine.yml comments https://github.com/ClearSkyTeam/ClearSky/pull/416
- [x] Fix skins in 0.15

Notes: From now on I will do more with git (Or GUI's for git) but not the website

**Comment by robske110** [comment]
In other words I'm planning to get realy active

**Comment by kam187** [comment]
Can you fix the give/enchant too.  The inventory gets messed up if you give yourself something and try to enchant it.  It's stopping me being able to use clearsky at the moment.

**Comment by robske110** [comment]
I think @thebigsmileXD is already on it...
Let's make this an general assignment list now

**Comment by robske110** [comment]
@kam187 has been fixed

**Comment by thebigsmileXD** [comment]
Don't post already known issues in other issues

**Comment by thebigsmileXD** [comment]
And:

**Comment by Aericio** [comment]
wat lol

**Comment by thebigsmileXD** [comment]
*cough* update or close

**Comment by robske110** [comment]
Well it's kinda up to date, will now add my redstone todo

**Comment by Aericio** [comment]
u shud rewrite the things frum genizyz

**Comment by robske110** [comment]
What should i rewrite?

**Comment by robske110** [comment]
Add:
http://robskebueba.no-ip.biz/directPhar.php?branch=php7

**Comment by remotevase** [comment]
Isn't this project kinda dead?

**Comment by Aericio** [comment]
Sorry, isn't ImagicalMine already dead? Keep to your own project.

**Comment by remotevase** [comment]
@Aericio I don't wanna make enemies so okay I will... And @caspervanneck :P

**Comment by thebigsmileXD** [comment]
Todo: move back CS
